### ISSUE TITLE
Using module in the scripting environment

### ISSUE THREAD

**Issue by gamesbook** [vpoulailleau/simplelogging#36]
* Simple Logging version: 0.9.0
* Python version: 2.7
* Operating System: Ubuntu 16.04

### Description

Unable to use in the scripting environment

### What I Did

Started the scripting environment via `python`
```
>>> import simplelogging
>>> logger = simplelogging.get_logger()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/simplelogging/__init__.py", line 42, in get_logger
    caller_name = caller_module.__name__
AttributeError: 'NoneType' object has no attribute '__name__'
```

**Comment by vpoulailleau** [comment]
Python 2.7 is not tested. I forgot to mention that I didn't plan to support Python 2.7 which is almost obsolete (https://pythonclock.org/).

I'll try to look closer at your problem this week (or maybe anyone is interested in solving this issue, send a PR). I don't have an answer at the first glance (except, switch to Python 3 ;-) )

**Comment by vpoulailleau** [comment]
I obviously don't have the time to support Python 2 (previous comment was several months ago…). And Python 2 end of life is planned in three months, so I close the issue. It's better for everybody to switch to Python 3, but I do accept any pull request for Python 2 support.
