### ISSUE TITLE
New release 

### ISSUE THREAD

**Issue by jorisoffouga** [vpoulailleau/simplelogging#88]
I try to add simplelogging in Buildroot : http://lists.busybox.net/pipermail/buildroot/2019-September/259453.html.

But this requires a release with the following commit 
https://github.com/vpoulailleau/simplelogging/commit/43804d1d286b97fdb80299ccc2cfd4c7826624c8

Best regards,
Joris Offouga

**Comment by vpoulailleau** [comment]
@jorisoffouga @yegorich Here it is: version 0.10.0 is now available (https://pypi.org/project/simplelogging/0.10.0/). I let you interact with Buildroot mailing list.

Note that this version deprecates Python 3.4 support (though, it should continue to work as before with this release).

**Comment by jorisoffouga** [comment]
Thanks @vpoulailleau

**Comment by vpoulailleau** [comment]
You're welcome ;-)
